### PR TITLE
Using viper for config reload and code restructuring

### PR DESCRIPTION
**Pull request by tsheasha**
This addresses #14 and #10

### CODE REVIEW

**Comment by tsheasha** [comment]
Will add the config changes to viper here as well

**Comment by bobtfish** [comment]
Nice.

Can you link me to a doc describing how I *should* have been doing it, so that I can educate myself?

I'll try to look at this tonight, but it may be tomorrow due to post hackathon death ;)

**Comment by tsheasha** [comment]
@bobtfish sure, here is the link from the godocs https://golang.org/doc/code.html . It kight be a long read but it is a really interesting one imho.

**Comment by bobtfish** [comment]
Perfect, just what I was looking for, thanks <3

**Comment by bobtfish** [comment]
Ok, I've re-read that (I'd already read it previously), and I now double don't grok what you're doing.

Taken from that doc:

  * Go programmers typically keep all their Go code in a single workspace.
  * A workspace contains many version control repositories (managed by Git, for example).

Which means my 'workspace' is /Users/tdoran/go, and I have AWSnycast checked out in /Users/tdoran/go/src/github.com/bobtfish/AWSnycast

You seem to be adding an additional src/ directory *inside* the AWSnycast repository here, which, to me, implies you're setting your GOPATH (i.e. workspace) to be the root of the AWSnycast checkout. That seems (as I'm reading it) to completely contradict the two points above...

So I'm super confused / don't get it - I've also not seen *any* Go projects which have a src/ directory inside the repos that they stick things in - this certainly isn't how @mikepea is doing it in his projects, or how Hashicorp are doing it in their projects, or for their inter-project references (as a couple of examples).

I feel like one of us is missing a major clue here, and I suspect it's me: so I apologize that you're going to need to (further) deploy the clue-bat; however I'm afraid I need additional convincing before I can :thumbsup: to merging this :/

**Comment by bobtfish** [comment]
I'm trying this branch out, and I just can't get it to work for me.

When I'm at the root of the AWSnycast checkout:

    ⭐  gom test
    can't load package: package github.com/bobtfish/AWSnycast: no buildable Go source files in /Users/tdoran/gocode/src/github.com/bobtfish/AWSnycast
    gom:  exit status 1

if I cd src/AWSnycast/

    ⭐ gom test
    daemon/daemon.go:12:2: cannot find package "github.com/spf13/viper" in any of:
        /usr/local/go/src/github.com/spf13/viper (from $GOROOT)
        /Users/tdoran/gocode/src/github.com/bobtfish/AWSnycast/_vendor/src/github.com/spf13/viper (from $GOPATH)
        /Users/tdoran/gocode/src/github.com/bobtfish/AWSnycast/src/github.com/spf13/viper
        /Users/tdoran/gocode/src/github.com/spf13/viper
    gom:  exit status 1

And if I try:

    ⭐ make test
    bin/gom test -short ./...
    make: bin/gom: No such file or directory
    make: *** [test] Error 1

As noted before, my GOPATH is /Users/tdoran/go

If I instead do:

    export GOPATH=/Users/tdoran/go/src/github.com/bobtfish/AWSnycast
    go get github.com/mattn/gom
    bin/gom install
    make test

then things mostly work (so I assume that's what you're doing), however this doesn't appeal as a workflow to me as I would need to reset my GOPATH for each project as I come to work on it, rather than have the toolchain 'just work' with one single setting.

Also, it appears to be testing a bunch of stuff that isn't mine (like gom itself), and this fails:

    ⭐  make test
    bin/gom test -short ./...
    ?   	AWSnycast	[no test files]
    ok  	AWSnycast/aws	0.012s
    ok  	AWSnycast/config	0.013s
    ok  	AWSnycast/daemon	0.097s
    ok  	AWSnycast/healthcheck	0.340s
    ok  	AWSnycast/instancemetadata	0.009s
    ?   	AWSnycast/testhelpers	[no test files]
    ok  	AWSnycast/tests/integration	0.033s
    ok  	AWSnycast/utils	0.013s
    ok  	github.com/daviddengcn/go-colortext	0.011s
    ok  	github.com/hashicorp/go-version	0.012s
    --- FAIL: TestGomfile (0.02s)
        gen_test.go:59: Expected /var/folders/qg/8f4w7qbs3w1grgcbq8cw1m8mxx1rlh/T/gom703107879/_vendor, but false:
    FAIL
    FAIL	github.com/mattn/gom	0.059s
    ok  	github.com/mattn/gover	0.031s
    ?   	github.com/mattn/gover/cmd/gover	[no test files]
    gom:  exit status 1
    make: *** [test] Error 1

I note that gom itself doesn't appear to be laid out with a src/ directory inside it's repository either, it just has the go files at the top level (which is all groovy and works find with my GOPATH).

**Comment by tsheasha** [comment]
Hey @bobtfish let me shed some light on what i intended with this change.

First of all, I need to acknowledge, yes you are right, this layout does **not** work for the typical go dev that has their workspace structure and GOPATH setup properly. However, the change I did here was to make it work for both the typical and non-typical dev, that just wants to hack on the project.

The approach was to make AWSnycast root be the $GOPATH. and place the code inside src/AWSnycast, which would allow for fancier imports such as import "AWSnycast/daemon" in contrast to import "github.com/bobtfish/AWSnycast/daemon". This fancier import is not *just* fancy it is functional as well, expecially for those that decode to hack on their own fork of the project. The build then will not really  work since they will need to change all occurrences of github.com/bobtfish/ with github.com/$username/, or so I have experienced.

What this means is hacking on this project will not be limited to an experienced go dev, and this comes due to the change I introduced to the Makefile that sets the GOPATH during the make to be the cwd, i.e. the root of this project. (this setting is not global, so it will not overwrite your exported GOPATH value, it will just be the one used for that Makefile.

Now to the reason why this did not work for you, I believe the GOPATH setting you have made the GOBIN path be GOPATH/bin and since this is not the root of this repository, the Makefile failed to find gom in bin/gom. Changing that to just gom in the Makefile would work for you.

I can see why this might hinder those who are more used to the *correct* workspace structure. I would agree to close this PR and create a new one using gom , and the viper config change. Makes sense?

**Pull request closed without merging**
