### PR TITLE
Use viper for config

### PR DESCRIPTION
**Pull request by tsheasha**
This makes it possible to gracefully reset the application whenever a config file changes, without a need to restart the service.

### CODE REVIEW

**Comment by tsheasha** [comment]
@bobtfish I have no clue how to make this `godep save` command work, each time I run it it removes all the Godeps dir and adds an empty Godeps.json file.
Can you please advise?, since I need to add viper as a dependency here.

**Comment by bobtfish** [comment]
I'd suspect the issue is due to me having upgraded to go 1.6 (and having not touched godep since) - however I have no idea offhand.

I'm about to crash out, and my tomorrow/Monday is crazy so I may not get to it, however I'll try to work this out for you ASAP (Tuesday latest).

**Comment by tsheasha** [comment]
Thanks!, in the meantime I am using travis as my testbed for future commits :)

**Comment by bobtfish** [comment]
Welp, looks like godep is just fucked on go 1.5/1.6.

**Comment by bobtfish** [comment]
I've pushed a use_viper_configs branch to origin that just removes godep, however it fails tests - I'm not sure if this is due to your viper changes, or due to godep removal, and I'm *actually* done for the evening now :/

**Comment by tsheasha** [comment]
Definitely my changes :/ ... Will look into them tomorrow

**Comment by bobtfish** [comment]
Sweet, if I get *any* time (which isn't certain), I'll backport the godep removal into master.

I started using it on the basis that I wanted to make it *easier* for random other people to hack on the code (i.e. just clone the repos and have what you need), however in practice I think it's currently achieving the opposite of that!

**Comment by tsheasha** [comment]
gom might be a viable alternative ... will place an issue for it

**Pull request closed without merging**
